apiVersion: v1
kind: Service
metadata:
  name: mongo-express-service
spec:
  selector:
    app: mongo-express
  type: LoadBalancer # this type makes the service external (accessible from outside of the cluster)
  ports:
    - protocol: TCP
      port: 8081
      targetPort: 8081
      nodePort: 30000 # This would be the external port to access the service - could be in this range: 30000-32767